services:
  identity-service-db:
    image: mariadb
    restart: always
    container_name: 'Ofuq-mariadb'
    environment:
      MYSQL_DATABASE: 'identity_service'
      MYSQL_USER: 'ofuq'
      MYSQL_PASSWORD: 'Test123456_'
      MYSQL_ROOT_PASSWORD: 'Test123456_root'

    ports:
      - "3307:3306"
    volumes:
      - ./.docker-compose/data/mariadb-data:/var/lib/mysql

  postgres:
    image: postgres
    restart: always
    container_name: 'Ofuq-postgres'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'user1'
      POSTGRES_PASSWORD: 'Test123456_'
    ports:
      - "5432:5432"
    volumes:
      - ./.docker-compose/data/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    container_name: 'Ofuq-redis'
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-compose/data/redis-data:/data

  ofuq-identity:
    image: ofuq-identity
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    container_name: 'Ofuq-identity'
    ports:
      - "5000:80"
    depends_on:
      - identity-service-db
      - redis
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=mysql;User=user1;Password=Test123456_;"
      ConnectionStrings__RedisConnection: "localhost:6379"
    networks:
      - app-network

  ofuq-eureka:
    image: ofuq-eureka
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: 'Ofuq-eureka'
    ports:
      - "8761:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge